version: "3.9"
services:
  database:
    image: postgres:14.2
    container_name: database
    env_file: ./.env.dev
    ports:
      - 5432:5432

  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: bot
    volumes:
      - .:/usr/src/luna_bot/
    env_file: ./.env.dev
    environment:
      - DEBUG=1
    depends_on:
      - database
