version: "3.9"
services:
  bot:
    # Build from Dockerfile
    # Note: comment `image`
    #
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.prod
    image: twylix/luna_bot
    container_name: bot
    env_file: ./.env.production
    networks:
      - luna_network

networks:
  luna_network:
    driver: bridge
    name: luna_network
