version: "3.9"
services:
  database:
    image: postgres:14.2
    container_name: database
    volumes:
      - ./shared/postgres-data-dev/:/var/lib/postgresql/data/
    env_file: ./.env.dev
    ports:
      - 5432:5432

  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: bot
    volumes:
      - .:/usr/src/luna_bot/
    env_file: ./.env.dev
    depends_on:
      - database
