# Pull image
FROM python:3.9.8-alpine

# Env vars
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set workdir
WORKDIR /usr/src/luna_bot

# Copy project
COPY . .

# Project dependencies
RUN apk update
RUN apk add postgresql-dev gcc libpq python3-dev musl-dev libffi-dev git
RUN python -m pip install poetry 
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-dev

RUN chmod +x /usr/src/luna_bot/docker/entrypoint.dev.sh

# Entrypoint
ENTRYPOINT ["/bin/sh", "/usr/src/luna_bot/docker/entrypoint.dev.sh"]